import { bookLinks_func } from '$utils/book-now-links';
import { burger_btn } from '$utils/burger_btn';
import { initCityDetector } from '$utils/city-detector';
import { contacts_redirect } from '$utils/contacts_redirect';
import { countryInput_func } from '$utils/country-input';
import { currentCity_input } from '$utils/currentCity_input';
import { dates } from '$utils/dates_redirect';
import { initExpParams } from '$utils/exp-catalog-params';
import { expSelector_func } from '$utils/exp-selector';
import { expSliderLinkCreator_func } from '$utils/exp-slider-link-creator';
import { expVideoOnHover_func } from '$utils/exp-video-on-hover';
import { catalogItemExp_func } from '$utils/exp-video-on-hover-catalog-page';
import { experienceStateFilter_func } from '$utils/experience-state-filter';
import { faqHider_func } from '$utils/faq-hider';
import { footer_yer } from '$utils/footer-year';
import { formSelectors_func } from '$utils/form-selectors';
import { giftCard_redirect } from '$utils/giftCard_redirect';
import { menuSelectorMobile_func } from '$utils/main-page-city-selector-mobile';
import { menuColor_func } from '$utils/menu-color';
import { mobile_menu } from '$utils/mobile_menu';
import { selectionAllButton_func } from '$utils/selection-all-button';
import { coloredSlider_func } from '$utils/sliders-colors';
window.Webflow ||= [];
window.Webflow.push(() => {
  initCityDetector();
  formSelectors_func();
  initExpParams();
  coloredSlider_func();
  expSliderLinkCreator_func();
  expVideoOnHover_func();
  catalogItemExp_func();
  menuColor_func();
  menuSelectorMobile_func();
  expSelector_func();
  faqHider_func();
  bookLinks_func();
  experienceStateFilter_func();
  selectionAllButton_func();
  countryInput_func();
  footer_yer();
  giftCard_redirect();
  mobile_menu();
  currentCity_input();
  burger_btn();
  contacts_redirect();
  dates();
});
